services:
  mongodb:
    container_name: mongodb_teste_frontend
    image: mongo:8.0.3
    ports:
      - 27030:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
    restart: unless-stopped
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./db_data:/data/db